apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cbull
  name: cbull-dev
  labels:
    app: cbull-dev
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: cbull-dev
  template:
    metadata:
      labels:
        app: cbull-dev
    spec:
      containers:
        - name: cbull-dev
          image: csbull55/cbull-dev:main-fe0afe17cfefbbf9ae0a0295c25807760d58ea8f
