apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cbull-dev
  namespace: cbull-dev
  labels:
    app: cbull-dev
  annotations:
    acme.cert-manager.io/http01-ingress-class: external
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  ingressClassName: external
  rules:
    - host: cbull.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: cbull-dev
              servicePort: 80
  tls:
    - hosts:
      - cbull.dev
      secretName: cbull-dev-acme-certificate